version: "3.7"

services:
  database_sharecode:
    image: postgres:14
    container_name: database_sharecode
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sharecodeadmin
      - POSTGRES_PASSWORD=sharecode2022
      - POSTGRES_DB=sharecodeDB
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local
