version: "3.7"

services:
  database_sharecode:
    image: postgres
    container_name: database_sharecode
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sharecodeadmin
      - POSTGRES_PASSWORD=sharecode2022
      - POSTGRES_DB=sharecodeDB
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: sharecode
    ports:
      - 3333:3333

    volumes:
      - .:/usr/app
    links:
      - "database_sharecode"
    depends_on:
      - "database_sharecode"

volumes:
  pgdata:
    driver: local
